version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=password
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    networks:
      - client_net
      - seller_net

volumes:
  elastic_data:

networks:
  client_net:
    driver: bridge
  seller_net:
    driver: bridge
    external: true

