version: '3.8'

services:
  mongo:
    extends:
      file: docker-compose-mongo.yml
      service: mongo

  zookeeper:
    extends:
      file: docker-compose-kafka.yml
      service: zookeeper
  
  kafka:
    extends:
      file: docker-compose-kafka.yml
      service: kafka
    depends_on:
     - zookeeper
  
  elasticsearch:
    extends:
      file: docker-compose-elastic.yml
      service: elasticsearch

  api:
    extends:
      file: docker-compose-api.yml
      service: api
    depends_on:
      - mongo
      - kafka
      - elasticsearch

  # app:
  #   extends:
  #     file: docker-compose-app.yml
  #     service: app
  #   depends_on:
  #     - api

volumes:
  mongo-data:
  elastic_data:

networks:
  client_net:
    driver: bridge
  seller_net:
    driver: bridge
    external: true
  kafka_net:
    driver: bridge 
